#
# HPC REST API Server configuration
#
HPC_REST_API_SERVER:
  hostname: 0.0.0.0
  port: 8000
  sudo:
    exec_syscall_path: 'command/exec_syscall'
    exec_cmd_timeout: 250
    sudo_path: '/usr/bin/sudo'
    timeout_path: '/usr/bin/timeout'
  x509_usermap: 'config/x509_usermap'
  system_type: "fugaku"
  ssl_client_s_dn: "x-ssl-client-s-dn"
  ssl_client_verify: "x-ssl-client-verify"
  version: '0.1.0'


#
# HPC REST API configuration
#
HPC_REST_API:
  version: '0.1.0'


#
# Logging configuration
#
LOGGING:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
      datefmt: '%Y/%m/%d %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: DEBUG
      stream: ext://sys.stdout
    file:
      class: logging.FileHandler
      formatter: simple
      filename: /var/log/rest_api_server.log
      mode: a
  loggers:
    root:
      level: DEBUG
      handlers: [console]
      propagate: no
    api:
      level: INFO
      handlers: [console, file]
      propagate: 0
      qualname: api
  root:
    level: DEBUG
    handlers: []
